# 2024 - 12 - 27

In [4]:
score = 70
if score >= 60:
    message = 'success'
else:
    message = 'failure'
print(message)

score = 50
message = 'hi' if score >= 60 else 'hello'
print(message)

success
hello


## 리스트 컴프리헨션
### [표현식 for 항목 in iterable]
### 표현식 : 각 항목을 처리한 후 생성할 값을 지정
### for 항목 in iterable : 반복할 대상(iterable, 예 : 리스트, 문자열 등)

In [5]:
numbers = [1,2,3,4]
squares1 = []
for x in numbers:
    squares1.append(x**2)
print(squares1)
squares2 = [x**2 for x in numbers]
print(squares2)

[1, 4, 9, 16]
[1, 4, 9, 16]


In [16]:
numbers = [1,2,3,4,5,6,7]
even_numbers = []
even_numbers = [x for x in numbers  if x % 2 == 0 ]
print(even_numbers)

[4, 16, 36]


# 넘파이(Numpy)
#### python 리스트에는 배열에 실제 데이터의 주소가 담겨있음 (속도 느림)
#### numpy 배열은 실제 데이터가 배열에 들어있음 (속도 빠름,대규모 연산 유용)

In [37]:
import numpy as np
list = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(list)
b = np.arange(0,10)
print(a)
print(b)
print(a.shape)      #크기
print(a.ndim)       #차원
c = a.reshape(1,-1)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
(3, 3)
2
[[1 2 3 4 5 6 7 8 9]]


### numpy 배열의 shape이 같다면 사칙연산 가능

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [50]:
a = np.zeros([3,3])
b = np.ones([3,3])
c = np.eye(3)
print(a); print(b); print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
list_data_1 = [1,'2',3]
list_data_2 = [1, 2, 3]
arr_1 = np.array(list_data_1)
arr_2 = np.array(list_data_2)
print(arr_1)
print(arr_2)
print(arr_1.shape)
print(arr_2.shape)
print(type(arr_1))
print(type(arr_2))

['1' '2' '3']
[1.  2.2 3. ]
(3,)
(3,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [59]:
np.zeros([2,4],dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [84]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
print(arr)
print(arr.ndim)
print(arr.shape)
print('\n')
arr = np.reshape(arr,(1,2,-1))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
3
(3, 2, 4)


[[[ 1  2  3  4  5  6  7  8  9 10 11 12]
  [13 14 15 16 17 18 19 20 21 22 23 24]]]


In [86]:
a = [1,2,3]
b = np.array([1,2,3])
print(a*3)
print(b*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [102]:
###################리스트 for문 사용###############
data_1 = [[[0,1,2,3,4,5,6,7,8,9],[[0,1,2,3,4,5,6,7,8,9]],[0,1,2,3,4,5,6,7,8,9]]]
data_2 = np.array([[[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]]])
data = [0,1,2,3,4,5,6,7,8,9]
a = []
for i in data:
    a.append(i*2)
print(a)
###################리스트 컴프리헨션 사용###############
li = [i*2 for i in data]
print(li)
###################array 사용###############
arr = np.array(data)
print(arr*2)

print(len(data_1),len(data_1[0]),len(data_1[0][0]))
print(data_2.ndim,data_2.shape,data_2.size)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]
1 3 10
3 (1, 3, 10) 30


In [109]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1],'\n')
b = np.array([[0,1,2],[3,4,5]])
print(b[0, 0])
print(b[0, 1])
print(b[1, -1])

2
4 

0
1
5


In [122]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print()
print(a[1,1:])
print(a[ :2, :2])


[5 6 7]
[[0 1]
 [4 5]]


In [128]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a+b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


## 팬시 인덱싱(fancy indexing)
#### 대괄호 '[]' 안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또 다른 ndarray 배열을 받을 수 있음
#### 1. 불리언(Boolean) 배열 방식


In [132]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,
                False,True,False,True,False])
print(a[idx])

[0 2 4 6 8]


In [141]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a % 2 == 0)
b = a % 2 == 0
print(a[a % 2 == 0])
print(a[b])

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[0 2 4 6 8]


#### 2. 정수 배열 방식

In [142]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
print(a[idx])

[11 33 55 77 99]
